### ISSUE TITLE
About coco dataset script

### ISSUE THREAD

**Issue by torchmyheart** [zhenyuw16/noisyboundaries#2]
Hello, it's a nice work. I want to train on coco.
```
mkdir labels
python scripts/coco/prepare_coco_data.py --percent 20 --seed 1
bash tools/dist_train.sh configs/noisyboundaries/coco/mask_rcnn_r50_fpn_1x_coco_sup.py 1
```
I run the above command but get an error:
`FileNotFoundError: [Errno 2] No such file or directory: 'data/coco/annotations/instances_train2017.1@10.json'`
Here it needs 10 percent of the annotation file, but I can't find where to set 20.
Where can I set the percent of coco？

Thanks

**Comment by torchmyheart** [comment]
Could you supplement README about coco? 
Thank u very much

**Comment by zhenyuw16** [comment]
run python scripts/coco/prepare_coco_data.py --percent 10 --seed 1, then you can get the 10 percent of the annotation.
We will update README soon. The basic running pipeline is the same.

**Comment by torchmyheart** [comment]
yes I did it, but I want to try 20%. I can't find where to set 20. Thank you for your efforts

**Comment by torchmyheart** [comment]
> yes I did it, but I want to try 20%. I can't find where to set 20. Thank you for your efforts

oh, I find it in `configs/_base_/datasets/coco_instance_sup.py`

**Comment by torchmyheart** [comment]
@zhenyuw16   I'm too dumb. Could you explain the purpose of each file?
filter_pl.py
form_ann.py
pkl2json.py
Looking forward to your reply
