### ISSUE TITLE
About the coco dataset pseudo label config

### ISSUE THREAD

**Issue by torchmyheart** [zhenyuw16/noisyboundaries#5]
Hello, I have a question, why 10% dataset is repeated 19 times here

https://github.com/zhenyuw16/noisyboundaries/blob/0c83823fe3634edb1274f4b20829822e49a25d65/configs/_base_/datasets/coco_instance_pl.py#L65-L76 

Looking forward to your reply. Thank you

**Comment by zhenyuw16** [comment]
We find that in some situation, when the ratio of labeled images and unlabeled images is 2:1, the performance can be better. However, most of times, this does not affect the performance. When the  repeated time is 9, the ratio of labeled images and unlabeled images is about 1:1. As I know the performance would not change significantly.

**Comment by torchmyheart** [comment]
OK, I got it, thank u very much
